name: Build IDDCX Driver Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [x64, ARM64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Check Chocolatey installation
        run: choco --version

      - name: Install Visual Studio 2022 dependencies
        run: |
          choco install visualstudio2022-workload-manageddesktop -y
          choco install visualstudio2022-workload-nativedesktop -y
          choco install visualstudio2022-workload-vctools -y

      - name: Build the IDDCX driver
        run: |
          msbuild DriverProject.sln /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }}

      - name: List build directory
        run: dir build\${{ matrix.configuration }}\${{ matrix.platform }}

      - name: Upload built driver
        uses: actions/upload-artifact@v3
        with:
          name: Built-Driver-${{ matrix.configuration }}-${{ matrix.platform }}
          path: build\${{ matrix.configuration }}\${{ matrix.platform }}\driver.sys
